services:
  # 1. PostgreSQL (Relational SQL Persistence)
  postgres:
    image: postgres:15-alpine
    container_name: fulfillment-postgres
    environment:
      POSTGRES_DB: fulfillmentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fulfillment-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fulfillmentdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Redis (NoSQL Caching Layer)
  redis:
    image: redis:7-alpine
    container_name: fulfillment-redis
    ports:
      - "6379:6379"
    networks:
      - fulfillment-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 3. Splunk Enterprise (Local Log Aggregation & Analytics Dashboard)
  splunk:
    image: splunk/splunk:latest
    platform: linux/amd64
    container_name: fulfillment-splunk
    tty: true
    stdin_open: true
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
      - SPLUNK_PASSWORD=SplunkPassword123
      - PYTHONUNBUFFERED=1
      - ANSIBLE_FORCE_COLOR=0
      - ANSIBLE_NOCOLS=1
    ports:
      - "8000:8000"
      - "8088:8088"
    networks:
      - fulfillment-network
    volumes:
      - splunk_data:/opt/splunk/var
      - app_logs:/var/log/fulfillment-service

  # 4. Resilient Fulfillment Microservice (Java / Linux Runtime)
  fulfillment-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fulfillment-app
    ports:
      - "8080:8080"
    volumes:
      - app_logs:/var/log/fulfillment-service
    environment:
      DB_URL: "jdbc:postgresql://postgres:5432/fulfillmentdb"
      DB_DRIVER: "org.postgresql.Driver"
      DB_USER: "postgres"
      DB_PASSWORD: "postgrespassword"
      DB_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      LOGGING_FILE_PATH: "/var/log/fulfillment-service"
      SPLUNK_HEC_URL: "http://splunk:8088/services/collector/event"
      SPLUNK_HEC_TOKEN: ${SPLUNK_HEC_TOKEN}
    networks:
      - fulfillment-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  splunk_data:
  app_logs:

networks:
  fulfillment-network:
    driver: bridge